# Generated by Django 5.0.6 on 2024-12-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
