# Generated by Django 5.0.6 on 2025-01-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_userprofile_is_completed_userprofile_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_completed',
        ),
    ]
