# Generated by Django 5.0.6 on 2025-01-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_userprofile_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_updated',
        ),
    ]
