# Generated by Django 5.0.6 on 2025-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_examrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='test',
            name='github_link',
        ),
        migrations.AddField(
            model_name='question',
            name='mcq_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('CODE', 'Code-Based Question')], default='MCQ', max_length=50),
        ),
    ]
