# Generated by Django 5.0.6 on 2025-01-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0007_rename_text_question_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='mcq_options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='code_editor_placeholder',
            field=models.TextField(blank=True, help_text='Placeholder text for code editor in code-based questions.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='For MCQs, provide 4 options as a JSON array.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('CODE', 'Code-Based Question')], default='MCQ', max_length=10),
        ),
    ]
