# Generated by Django 5.0.6 on 2025-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0008_rename_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code_editor_placeholder',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(help_text='Correct answer or solution'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for MCQ', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CODE', 'Code-Based')], default='MCQ', max_length=10),
        ),
    ]
