# Generated by Django 5.0.6 on 2025-01-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0011_alter_answer_answer_alter_answer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
